# yaml-language-server: $schema=https://gist.githubusercontent.com/sargunv/c2ca41a08391cd06feaad97aece309e4/raw/empty-json-schema.json
# ================================================================
# golangci-lint configuration for Stiva
# ================================================================

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (io.Closer).Close
      - os.Remove
      - os.RemoveAll
      - (*go.etcd.io/bbolt.DB).Close
      - (net.Listener).Close
      - (*net.TCPListener).Close

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - ineffassign
